function dateFromParts(day,month,year,hour=0,minute=0,second=0){if(!validDateParts(day,month,year))return null;const d=new Date(year,month-1,day,hour,minute,second);return isNaN(d.getTime())?null:d}

function parseDatePartsText(value){const s=clean(value).replace(/\u00a0/g," ").replace(/\s+/g," ");if(!s)return null;const match=s.match(/(\d{1,4})[\/\-.](\d{1,2})[\/\-.](\d{1,4})/);if(!match)return null;const a=+match[1],b=+match[2],c=+match[3];let day,month,year;if(a>=1000){year=a;month=b;day=c}else if(c>=1000){year=c;if(b>12){month=a;day=b}else if(a>12){day=a;month=b}else{month=a;day=b}}else return null;return validDateParts(day,month,year)?{day,month,year}:null}

function dateVal(v){if(v instanceof Date&&!isNaN(v.getTime()))return v;const s=clean(v);if(!s)return"";if(/^\d+(?:\.\d+)?$/.test(s)){const n=+s;if(n>0&&n<100000){const d=new Date(Date.UTC(1899,11,30)+n*86400000);if(!isNaN(d.getTime()))return new Date(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate(),d.getUTCHours(),d.getUTCMinutes(),d.getUTCSeconds())}}const p=parts(v);if(p){const d=dateFromParts(p.day,p.month,p.year,p.hour||0,p.minute||0,p.second||0);if(d)return d}const d=new Date(s);return isNaN(d.getTime())?s:d}

function parts(v){if(v instanceof Date&&!isNaN(v.getTime()))return{day:v.getDate(),month:v.getMonth()+1,year:v.getFullYear(),hour:v.getHours(),minute:v.getMinutes(),second:v.getSeconds()};const s=clean(v).replace(/\u00a0/g," ").replace(/\s+/g," ");if(!s)return null;if(/^\d+(?:\.\d+)?$/.test(s)){const n=+s;if(n>0&&n<100000){const d=new Date(Date.UTC(1899,11,30)+n*86400000);if(!isNaN(d.getTime()))return{day:d.getUTCDate(),month:d.getUTCMonth()+1,year:d.getUTCFullYear(),hour:d.getUTCHours(),minute:d.getUTCMinutes(),second:d.getUTCSeconds()}}}const p=parseDatePartsText(s);if(p){const tm=s.match(/(?:\s|T)(\d{1,2}):(\d{2})(?::(\d{2}))?\s*(AM|PM)?/i);let hour=0,minute=0,second=0;if(tm){hour=+tm[1];minute=+tm[2];second=+(tm[3]||0);const ap=(tm[4]||"").toUpperCase();if(ap){if(hour<1||hour>12)return null;if(hour===12)hour=0;if(ap==="PM")hour+=12}else if(hour>23)return null}return{...p,hour,minute,second}}const d=new Date(s);return isNaN(d.getTime())?null:{day:d.getDate(),month:d.getMonth()+1,year:d.getFullYear(),hour:d.getHours(),minute:d.getMinutes(),second:d.getSeconds()}}

function validDateParts(day,month,year){const d=new Date(year,month-1,day);return d.getFullYear()===year&&d.getMonth()===month-1&&d.getDate()===day}

function key(v){const p=parts(v);return p?[p.year,String(p.month).padStart(2,"0"),String(p.day).padStart(2,"0")].join("-"):""}

function displayDate(v){const d=dateVal(v);if(!(d instanceof Date)||isNaN(d.getTime()))return clean(v);let h=d.getHours(),a=h>=12?"PM":"AM";h=h%12||12;return d.getDate()+"-"+(d.getMonth()+1)+"-"+d.getFullYear()+" "+h+":"+String(d.getMinutes()).padStart(2,"0")+":"+String(d.getSeconds()).padStart(2,"0")+" "+a}

function parseITSMDate(v){if(v instanceof Date&&!isNaN(v.getTime()))return v;const s=clean(v);if(!s)return null;const m=s.match(/^(\d{1,2})[-\/](\d{1,2})[-\/](\d{4})(?:\s+(\d{1,2}):(\d{2})(?::(\d{2}))?\s*(AM|PM)?)?$/i);if(!m)return null;let h=+(m[4]||0),mi=+(m[5]||0),sec=+(m[6]||0),ampm=(m[7]||"").toUpperCase();if(h>23||mi>59||sec>59)return null;if(ampm){if(h>12||h<1)return null;if(h===12)h=0;if(ampm==="PM")h+=12}return dateFromParts(+m[1],+m[2],+m[3],h,mi,sec)}