function dateVal(v){if(v instanceof Date&&!isNaN(v))return v;const s=clean(v);if(!s)return"";if(/^\d+(?:\.\d+)?$/.test(s)){const n=+s;if(n>0&&n<100000&&XLSX.SSF?.parse_date_code){const p=XLSX.SSF.parse_date_code(n);if(p?.y&&p?.m&&p?.d)return new Date(p.y,p.m-1,p.d,p.H||0,p.M||0,p.S||0)}}const d=new Date(s);return isNaN(d) ? s:d}

function parts(v){if(v instanceof Date&&!isNaN(v))return{day:v.getDate(),month:v.getMonth()+1,year:v.getFullYear()};const s=clean(v).replace(/\s+/g," ");if(!s)return null;if(/^\d+(?:\.\d+)?$/.test(s)){const n=+s;if(n>0&&n<100000){if(XLSX.SSF?.parse_date_code){const p=XLSX.SSF.parse_date_code(n);if(p?.y&&p?.m&&p?.d)return{day:p.d,month:p.m,year:p.y}}const d=new Date(Date.UTC(1899,11,30)+n*86400000);if(!isNaN(d))return{day:d.getUTCDate(),month:d.getUTCMonth()+1,year:d.getUTCFullYear()}}}const months={jan:1,january:1,feb:2,february:2,mar:3,march:3,apr:4,april:4,may:5,jun:6,june:6,jul:7,july:7,aug:8,august:8,sep:9,sept:9,september:9,oct:10,october:10,nov:11,november:11,dec:12,december:12};let m=s.match(/^(\d{1,2})[\\/. -]([A-Za-z]{3,9})[\\/. -](\d{2,4})/);if(m){const day=+m[1],month=months[m[2].toLowerCase()],year=+m[3]+(m[3].length===2?2000:0);if(month&&year>=1000&&validDateParts(day,month,year))return{day,month,year}}m=s.match(/^(\d{4})[\\/. -](\d{1,2}|[A-Za-z]{3,9})[\\/. -](\d{1,2})/);if(m){const year=+m[1],month=months[m[2].toLowerCase()]||+m[2],day=+m[3];if(month&&validDateParts(day,month,year))return{day,month,year}}m=s.match(/^(\d{1,4})[\\/. -](\d{1,2})[\\/. -](\d{1,4})/);if(m){const a=+m[1],b=+m[2],c=+m[3],candidates=a>=1000?[[c,b,a]]:a>12?[[a,b,c]]:b>12?[[b,a,c]]:[[a,b,c],[b,a,c]];for(const x of candidates){if(x[2]>=1000&&validDateParts(x[0],x[1],x[2]))return{day:x[0],month:x[1],year:x[2]}}}const d=new Date(s);return isNaN(d)?null:{day:d.getDate(),month:d.getMonth()+1,year:d.getFullYear()}}

function validDateParts(day,month,year){const d=new Date(year,month-1,day);return d.getFullYear()===year&&d.getMonth()===month-1&&d.getDate()===day}

function key(v){if(v instanceof Date&&!isNaN(v))return v.getFullYear()+"-"+String(v.getMonth()+1).padStart(2,"0")+"-"+String(v.getDate()).padStart(2,"0");const s=clean(v).replace(/\s+/g," ");if(!s)return"";const us=s.match(/^(\d{1,2})[-\/](\d{1,2})[-\/](\d{4})/);if(us){let a=+us[1],b=+us[2],y=+us[3];let day,month;if(b>12){month=a;day=b}else if(a>12){day=a;month=b}else{month=a;day=b}if(validDateParts(day,month,y))return y+"-"+String(month).padStart(2,"0")+"-"+String(day).padStart(2,"0")}const p=parts(v);return p?[p.year,String(p.month).padStart(2,"0"),String(p.day).padStart(2,"0")].join("-"):""}

function displayDate(v){const d=dateVal(v);if(!(d instanceof Date)||isNaN(d))return clean(v);let h=d.getHours(),a=h>=12?"PM":"AM";h=h%12||12;return d.getDate()+"-"+(d.getMonth()+1)+"-"+d.getFullYear()+" "+h+":"+String(d.getMinutes()).padStart(2,"0")+":"+String(d.getSeconds()).padStart(2,"0")+" "+a}

function parseITSMDate(v){if(v instanceof Date&&!isNaN(v))return v;const s=clean(v);if(!s)return null;const m=s.match(/^(\d{1,2})[-\/](\d{1,2})[-\/](\d{4})(?:\s+(\d{1,2}):(\d{2})(?::(\d{2}))?\s*(AM|PM)?)?$/i);if(!m)return null;let h=+(m[4]||0),mi=+(m[5]||0),sec=+(m[6]||0),ampm=(m[7]||"").toUpperCase();if(h>23||mi>59||sec>59)return null;if(ampm){if(h>12||h<1)return null;if(h===12)h=0;if(ampm==="PM")h+=12}const d=new Date(+m[3],+m[2]-1,+m[1],h,mi,sec);return !isNaN(d)&&d.getFullYear()===+m[3]&&d.getMonth()===+m[2]-1&&d.getDate()===+m[1]?d:null}