(() => {
"use strict";
const ORG={kpmg:"KPMG Assurance and Consulting Services LLP",default:"Edgeverve Systems Limited- NaBFID"};
const OUT=["Tickets#","Created on","Department","Prioritytitle","Type","subject","Classification","Organization","Wing","Closedon","resolution_steps","Status"];
const SUMMARY=["Client","Closed","Pending on COE","Pending On Customer","Grand Total"];
const EXCLUDED=[/not\s+reporting/i,/devices\s+not\s+working/i,/devices\s+not\s+reporting/i];
const $=id=>document.getElementById(id);
let createdRows=[],closedRows=[],processedRows=[],reviewRows=[],availableDates=[],selectedDate="",cursor=new Date();
const el={fileInput:$("fileInput"),dropzone:$("dropzone"),fileName:$("fileName"),dateSelection:$("dateSelection"),reportDate:$("reportDate"),datePickerButton:$("datePickerButton"),datePickerValue:$("datePickerValue"),datePickerPopover:$("datePickerPopover"),calendarPrev:$("calendarPrev"),calendarNext:$("calendarNext"),calendarMonth:$("calendarMonth"),calendarHint:$("calendarHint"),calendarGrid:$("calendarGrid"),calendarToday:$("calendarToday"),processBtn:$("processBtn"),dateSelectionStatus:$("dateSelectionStatus"),reviewPanel:$("reviewPanel"),reviewBody:$("reviewBody"),reviewCount:$("reviewCount"),continueBtn:$("continueBtn"),cancelReviewBtn:$("cancelReviewBtn"),resultSection:$("resultSection"),previewBtn:$("previewBtn"),editBtn:$("editBtn"),copyTableBtn:$("copyTableBtn"),downloadBtn:$("downloadBtn"),copyEmailBtn:$("copyEmailBtn"),copySubjectBtn:$("copySubjectBtn"),emailPreview:$("emailPreview"),dataPanel:$("dataPanel"),dataTitle:$("dataTitle"),dataSubtitle:$("dataSubtitle"),dataHead:$("dataHead"),dataBody:$("dataBody"),saveBtn:$("saveBtn"),closePanelBtn:$("closePanelBtn")};
function clean(v){return v==null?"":String(v).trim()}
function val(r,c){const k=Object.keys(r||{}).find(h=>clean(h).toLowerCase()===c.toLowerCase());return k?clean(r[k]):""}
function has(rows,c){return rows.length&&Object.keys(rows[0]).some(h=>clean(h).toLowerCase()===c.toLowerCase())}
function dateVal(v){if(v instanceof Date&&!isNaN(v))return v;const s=clean(v);if(!s)return"";if(/^\d+(?:\.\d+)?$/.test(s)){const n=+s;if(n>0&&n<100000&&XLSX.SSF?.parse_date_code){const p=XLSX.SSF.parse_date_code(n);if(p?.y&&p?.m&&p?.d)return new Date(p.y,p.m-1,p.d,p.H||0,p.M||0,p.S||0)}}const d=new Date(s);return isNaN(d) ? s:d}
function parts(v){const s=clean(v);if(!s)return null;if(/^\d+(?:\.\d+)?$/.test(s)){const n=+s;if(n>0&&n<100000){const d=new Date(Date.UTC(1899,11,30)+n*86400000);return{day:d.getUTCDate(),month:d.getUTCMonth()+1,year:d.getUTCFullYear()}}}const m=s.match(/(\d{1,4})[\/\-.](\d{1,2})[\/\-.](\d{1,4})/);if(m){const a=+m[1],b=+m[2],c=+m[3],x=a>=1000?[c,b,a]:[a,b,c];if(x[2]>=1000)return{day:x[0],month:x[1],year:x[2]}}const d=new Date(s);return isNaN(d)?null:{day:d.getDate(),month:d.getMonth()+1,year:d.getFullYear()}}
function key(v){const p=parts(v);return p?[p.year,String(p.month).padStart(2,"0"),String(p.day).padStart(2,"0")].join("-"):""}
function displayDate(v){const d=dateVal(v);if(!(d instanceof Date)||isNaN(d))return clean(v);let h=d.getHours(),a=h>=12?"PM":"AM";h=h%12||12;return d.getDate()+"-"+(d.getMonth()+1)+"-"+d.getFullYear()+" "+h+":"+String(d.getMinutes()).padStart(2,"0")+":"+String(d.getSeconds()).padStart(2,"0")+" "+a}
function ordinal(n){return n%100>=11&&n%100<=13?n+"th":n+({1:"st",2:"nd",3:"rd"}[n%10]||"th")}
function emailDate(v){const p=parts(v);if(!p)return"";return ordinal(p.day)+" "+["January","February","March","April","May","June","July","August","September","October","November","December"][p.month-1]+" "+p.year}
function classify(s){const m=clean(s).match(/Domain:\s*([^|]*)/i);return m?clean(m[1])||"NABFID DC":"NABFID DC"}
function org(s){return /KPMG/i.test(clean(s))?ORG.kpmg:ORG.default}
function nab(r){return /nabfid/i.test(val(r,"subject"))||/nabfid/i.test(val(r,"Organization"))}
function soc(r){return val(r,"Type").toLowerCase()==="soc alert"}
function excluded(r){const s=val(r,"subject");return s&&EXCLUDED.some(p=>p.test(s))}
function status(r){return clean(val(r,"Status")).replace(/\s+/g," ").toLowerCase()}
function output(r){const s=val(r,"subject");return{"Tickets#":val(r,"Tickets#"),"Created on":dateVal(val(r,"Created on")),"Department":val(r,"Department"),"Prioritytitle":val(r,"Prioritytitle"),"Type":"SOC Alert",subject:s,"Classification":classify(s),"Organization":org(s),"Wing":val(r,"Wing"),"Closedon":dateVal(val(r,"Closedon")),"resolution_steps":val(r,"resolution_steps"),"Status":val(r,"Status")}}
function valid(rows,name){if(!rows.length)throw Error(name+" file is empty.");for(const c of["Tickets#","Created on","subject","Type"])if(!has(rows,c))throw Error(name+' file is missing "'+c+'".')}
async function read(file){const wb=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:false,cellNF:true,cellText:true});const sh=wb.Sheets[wb.SheetNames[0]];return{file,rows:XLSX.utils.sheet_to_json(sh,{defval:"",raw:true})}}
function reset(){createdRows=[];closedRows=[];processedRows=[];reviewRows=[];availableDates=[];selectedDate="";el.reportDate.value="";el.datePickerValue.textContent="Select a date";el.processBtn.disabled=true;el.dateSelection.classList.add("hidden");el.reviewPanel.classList.add("hidden");el.resultSection.classList.add("hidden");el.dataPanel.classList.add("hidden")}
async function handleFiles(files){if(files.length!==2)return alert("Please upload exactly 2 Excel files: Created and Closed.");if(typeof XLSX==="undefined")return alert("Excel engine is not loaded. Please refresh.");reset();el.fileName.textContent="Reading 2 workbooks…";try{const a=await Promise.all([...files].map(read));let c=a.find(x=>!has(x.rows,"resolution_steps")),d=a.find(x=>has(x.rows,"resolution_steps"));if(!c||!d)throw Error('Upload one Created file without "resolution_steps" and one Closed file containing "resolution_steps".');valid(c.rows,"Created");valid(d.rows,"Closed");createdRows=c.rows;closedRows=d.rows;availableDates=[...new Set(createdRows.map(r=>key(val(r,"Created on"))).filter(Boolean))].sort();if(!availableDates.length)throw Error('No valid "Created on" dates found in Created file.');cursor=new Date(+availableDates[0].slice(0,4),+availableDates[0].slice(5,7)-1,1);el.fileName.textContent="Ready: "+c.file.name+" + "+d.file.name;el.dateSelectionStatus.textContent="Created: "+createdRows.length.toLocaleString()+" records • Closed: "+closedRows.length.toLocaleString()+" records";el.dateSelection.classList.remove("hidden");calendar();}catch(e){reset();el.fileName.textContent="Processing failed";alert(e.message||e)}}
function calendar(){const y=cursor.getFullYear(),m=cursor.getMonth();el.calendarMonth.textContent=cursor.toLocaleDateString("en-US",{month:"long",year:"numeric"});el.calendarHint.textContent=availableDates.length+" available dates from Created file";el.calendarGrid.innerHTML="";const first=new Date(y,m,1),off=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),prev=new Date(y,m,0).getDate();for(let i=0;i<42;i++){let d=i-off+1,yy=y,mm=m,muted=false;if(d<1){mm--;if(mm<0){mm=11;yy--}d=prev+d;muted=true}else if(d>days){d-=days;mm++;if(mm>11){mm=0;yy++}muted=true}const k=yy+"-"+String(mm+1).padStart(2,"0")+"-"+String(d).padStart(2,"0"),b=document.createElement("button");b.type="button";b.textContent=d;if(muted)b.className="is-muted";if(availableDates.includes(k)){b.classList.add("is-available");b.onclick=()=>{el.reportDate.value=k;el.datePickerValue.textContent=new Date(yy,mm,d).toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"});el.processBtn.disabled=false;closeCal();calendar()}}if(k===el.reportDate.value)b.classList.add("is-selected");b.disabled=!availableDates.includes(k);el.calendarGrid.appendChild(b)}}
function closeCal(){el.datePickerPopover.classList.add("hidden");el.datePickerButton.setAttribute("aria-expanded","false")}
function eligibleCreated(d){return createdRows.filter(r=>key(val(r,"Created on"))===d).filter(nab).filter(soc).filter(r=>!excluded(r))}
function eligibleClosed(d){return closedRows.filter(r=>key(val(r,"Created on"))===d).filter(nab).filter(soc).filter(r=>!excluded(r)).filter(r=>!!val(r,"resolution_steps"))}
function processDate(){const d=clean(el.reportDate.value);if(!d)return alert("Please select a report date first.");selectedDate=d;const cr=eligibleCreated(d),cl=eligibleClosed(d),closedIds=new Set(cl.map(r=>val(r,"Tickets#")).filter(Boolean));const alreadyClosed=cr.filter(r=>status(r)==="closed");reviewRows=cr.filter(r=>status(r)!=="closed"&&!closedIds.has(val(r,"Tickets#"))).map(output);processedRows=cl.map(output);el.dateSelectionStatus.textContent=cr.length+" eligible Created records • "+alreadyClosed.length+" already Closed ignored • "+cl.length+" Closed records";if(reviewRows.length){renderReview();el.reviewPanel.classList.remove("hidden");el.resultSection.classList.add("hidden");el.reviewPanel.scrollIntoView({behavior:"smooth",block:"start"})}else finalize()}
function renderReview(){el.reviewCount.textContent=reviewRows.length+" ticket"+(reviewRows.length===1?"":"s")+" require review";el.reviewBody.innerHTML="";reviewRows.forEach(r=>{const tr=document.createElement("tr");for(const v of[r["Tickets#"],displayDate(r["Created on"]),r.subject,r.Status,r.Wing]){const td=document.createElement("td");td.textContent=v;tr.appendChild(td)}for(const [f,t] of[["Status","text"],["Wing","text"],["Closedon","datetime-local"],["resolution_steps","textarea"]]){const td=document.createElement("td"),i=document.createElement(t==="textarea"?"textarea":"input");if(t!=="textarea")i.type=t;i.value=f==="Closedon"&&r[f] instanceof Date&&!isNaN(r[f])?r[f].toISOString().slice(0,16):clean(r[f]);i.placeholder=f==="Status"||f==="Wing"?"Leave blank to keep current":"Leave blank to keep existing";i.oninput=e=>r[f]=f==="Closedon"&&e.target.value?new Date(e.target.value):e.target.value;td.appendChild(i);tr.appendChild(td)}el.reviewBody.appendChild(tr)})}
function finalize(){const map=new Map();processedRows.forEach(r=>map.set(clean(r["Tickets#"]),r));reviewRows.forEach(r=>{const id=clean(r["Tickets#"]);if(id&&!map.has(id))map.set(id,r)});processedRows=[...map.values()].filter(r=>r["Tickets#"]);el.reviewPanel.classList.add("hidden");renderSummary();el.resultSection.classList.remove("hidden");el.fileName.textContent="Processed: "+processedRows.length+" final records for "+emailDate(processedRows[0]?.["Created on"]);el.dateSelectionStatus.textContent="Final output: "+processedRows.length+" records • Created review records included: "+reviewRows.length;el.resultSection.scrollIntoView({behavior:"smooth",block:"start"})}
function summarize(rows){const m=new Map();rows.forEach(r=>{const c=clean(r.Classification)||"NABFID DC";if(!m.has(c))m.set(c,{Closed:0,"Pending on COE":0,"Pending On Customer":0,total:0});const s=m.get(c),x=status(r);if(x==="closed")s.Closed++;else if(x==="pending on coe")s["Pending on COE"]++;else if(x==="pending on customer")s["Pending On Customer"]++;s.total++});return m}
function cells(tr,a){a.forEach(v=>{const td=document.createElement("td");td.textContent=v;tr.appendChild(td)})}
function renderSummary(){const m=summarize(processedRows),h=$("summaryHead"),b=$("summaryBody");h.innerHTML="<tr>"+SUMMARY.map(x=>"<th>"+x+"</th>").join("")+"</tr>";b.innerHTML="";const t={Closed:0,"Pending on COE":0,"Pending On Customer":0,total:0};[...m.keys()].sort().forEach(c=>{const s=m.get(c);t.Closed+=s.Closed;t["Pending on COE"]+=s["Pending on COE"];t["Pending On Customer"]+=s["Pending On Customer"];t.total+=s.total;const tr=document.createElement("tr");cells(tr,[c,s.Closed,s["Pending on COE"],s["Pending On Customer"],s.total]);b.appendChild(tr)});const tr=document.createElement("tr");cells(tr,["Grand Total",t.Closed,t["Pending on COE"],t["Pending On Customer"],t.total]);b.appendChild(tr);renderEmail()}
function renderData(edit){el.dataPanel.classList.remove("hidden");el.saveBtn.classList.toggle("hidden",!edit);el.dataTitle.textContent=edit?"Edit processed data":"Preview processed data";el.dataHead.innerHTML="<tr>"+OUT.map(h=>"<th>"+h+"</th>").join("")+"</tr>";el.dataBody.innerHTML="";processedRows.forEach((r,i)=>{const tr=document.createElement("tr");OUT.forEach(h=>{const td=document.createElement("td");if(edit){const x=document.createElement("input");x.value=r[h] instanceof Date?displayDate(r[h]):r[h]||"";x.oninput=e=>r[h]=e.target.value;td.appendChild(x)}else td.textContent=h==="Created on"||h==="Closedon"?displayDate(r[h]):r[h]||"";tr.appendChild(td)});el.dataBody.appendChild(tr)})}
function table(){return document.querySelector("#summaryHead")?.closest("table")}
function styleCopy(t){t.style.cssText="border-collapse:collapse;width:auto;font-family:Inter,Arial,sans-serif;font-size:10pt";[...t.querySelectorAll("tr")].forEach((r,i,a)=>r.querySelectorAll("th,td").forEach(c=>c.style.cssText="border:1px solid #202020;padding:4px 8px;white-space:nowrap;text-align:center;background:"+(i===0||i===a.length-1?"#0B2A5B":"#FFFFFF")+";color:"+(i===0||i===a.length-1?"#FFFFFF":"#111827")+";font-weight:"+(i===0||i===a.length-1?"700":"400")));return t}
function fallback(t){const a=document.createElement("textarea");a.value=t;a.style.cssText="position:fixed;left:-9999px";document.body.appendChild(a);a.select();document.execCommand("copy");a.remove()}
async function copy(t,html){if(navigator.clipboard&&window.ClipboardItem){try{await navigator.clipboard.write([new ClipboardItem({"text/html":new Blob([html],{type:"text/html"}),"text/plain":new Blob([t],{type:"text/plain"})})]);return}catch(e){}}fallback(t)}
function copied(b,s){const o=b.textContent;b.textContent=s;setTimeout(()=>b.textContent=o,1600)}
async function copySummary(){const t=table();if(!t)return;const text=[...t.rows].map(r=>[...r.cells].map(c=>c.textContent.trim()).join("\t")).join("\n");await copy(text,styleCopy(t.cloneNode(true)).outerHTML);copied(el.copyTableBtn,"Copied ✓")}
function renderEmail(){if(!processedRows.length)return;const d=emailDate(processedRows[0]["Created on"]),t=table()?.cloneNode(true);if(!d||!t)return;styleCopy(t);const c=[...summarize(processedRows).keys()].sort();const ct=c.length<=1?(c[0]||""):c.slice(0,-1).join(", ")+" and "+c.at(-1);const sub=document.createElement("div");sub.className="email-subject-preview";sub.textContent="Subject: NABFID Daily Offense Report || "+d;const body=document.createElement("div");body.className="email-preview-body";const p1=document.createElement("p");p1.textContent="Hi Team,";const p2=document.createElement("p");p2.innerHTML="Please find the attached "+ct+" daily offense data for <strong>"+d+"</strong>.";body.append(p1,p2,t);el.emailPreview.replaceChildren(sub,body)}
async function copySubject(){if(!processedRows.length)return;await copy("NABFID Daily Offense Report || "+emailDate(processedRows[0]["Created on"]),"");copied(el.copySubjectBtn,"Subject Copied ✓")}
async function copyEmail(){renderEmail();const b=el.emailPreview.querySelector(".email-preview-body");if(!b)return;const t=[...b.querySelectorAll("p,tr")].map(x=>x.textContent.trim()).join("\n");await copy(t,b.outerHTML);copied(el.copyEmailBtn,"Email Copied ✓")}
function borders(){const s={style:"thin",color:{rgb:"202020"}};return{top:s,bottom:s,left:s,right:s}}
function styleSheet(sh,total=-1){const rg=XLSX.utils.decode_range(sh["!ref"]);for(let r=rg.s.r;r<=rg.e.r;r++)for(let c=rg.s.c;c<=rg.e.c;c++){const x=sh[XLSX.utils.encode_cell({r,c})];if(x)x.s=r===0?{font:{name:"Inter",sz:10,bold:true,color:{rgb:"FFFFFF"}},fill:{fgColor:{rgb:"0B2A5B"}},alignment:{horizontal:"center",vertical:"center"},border:borders()}:{font:{name:"Inter",sz:10,color:{rgb:r===total?"FFFFFF":"374151"}},fill:{fgColor:{rgb:r===total?"0B2A5B":"FFFFFF"}},alignment:{horizontal:"center",vertical:"center",wrapText:false},border:borders()}}}
function download(){if(!processedRows.length)return;const wb=XLSX.utils.book_new(),s=XLSX.utils.json_to_sheet(processedRows);for(const col of["B","J"])for(let r=2;r<=processedRows.length+1;r++){const c=s[col+r];if(c&&c.v instanceof Date)c.z="d-m-yyyy h:mm:ss AM/PM"}s["!freeze"]={xSplit:0,ySplit:1};s["!autofilter"]={ref:s["!ref"]};s["!cols"]=OUT.map(h=>({wch:({subject:42,Organization:38,resolution_steps:55,"Tickets#":16,"Created on":20,"Closedon":20,Wing:20}[h]||18)}));styleSheet(s);XLSX.utils.book_append_sheet(wb,s,"Offenses");const m=summarize(processedRows),rows=[SUMMARY],tot=[0,0,0,0];[...m.keys()].sort().forEach(c=>{const x=m.get(c);rows.push([c,x.Closed,x["Pending on COE"],x["Pending On Customer"],x.total]);tot[0]+=x.Closed;tot[1]+=x["Pending on COE"];tot[2]+=x["Pending On Customer"];tot[3]+=x.total});rows.push(["Grand Total",...tot]);const ss=XLSX.utils.aoa_to_sheet(rows);ss["!cols"]=[{wch:30},{wch:14},{wch:20},{wch:24},{wch:16}];styleSheet(ss,rows.length-1);XLSX.utils.book_append_sheet(wb,ss,"Classification");const p=parts(processedRows[0]["Created on"]),name=p?"NaBFID Offenses "+ordinal(p.day)+" "+["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sept","Oct","Nov","Dec"][p.month-1]+".xlsx":"NaBFID Offenses.xlsx";const blob=new Blob([XLSX.write(wb,{bookType:"xlsx",type:"array"})],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}),a=document.createElement("a"),u=URL.createObjectURL(blob);a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
function bind(){el.fileInput.onchange=e=>handleFiles(e.target.files);el.dropzone.ondragover=e=>{e.preventDefault();el.dropzone.classList.add("drop-active")};el.dropzone.ondragleave=()=>el.dropzone.classList.remove("drop-active");el.dropzone.ondrop=e=>{e.preventDefault();el.dropzone.classList.remove("drop-active");handleFiles(e.dataTransfer.files)};el.datePickerButton.onclick=()=>{if(el.datePickerPopover.classList.contains("hidden")){el.datePickerPopover.classList.remove("hidden");el.datePickerButton.setAttribute("aria-expanded","true");calendar()}else closeCal()};el.calendarPrev.onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()-1,1);calendar()};el.calendarNext.onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()+1,1);calendar()};el.calendarToday.onclick=()=>{const k=key(new Date());if(availableDates.includes(k)){el.reportDate.value=k;el.datePickerValue.textContent=new Date().toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"});el.processBtn.disabled=false}calendar()};document.addEventListener("click",e=>{if(!el.datePickerPopover.contains(e.target)&&!el.datePickerButton.contains(e.target))closeCal()});el.processBtn.onclick=processDate;el.continueBtn.onclick=finalize;el.cancelReviewBtn.onclick=()=>el.reviewPanel.classList.add("hidden");el.previewBtn.onclick=()=>{renderData(false);el.dataPanel.scrollIntoView({behavior:"smooth"})};el.editBtn.onclick=()=>{renderData(true);el.dataPanel.scrollIntoView({behavior:"smooth"})};el.copyTableBtn.onclick=copySummary;el.downloadBtn.onclick=download;el.copySubjectBtn.onclick=copySubject;el.copyEmailBtn.onclick=copyEmail;el.saveBtn.onclick=()=>{renderSummary();renderData(true)};el.closePanelBtn.onclick=()=>el.dataPanel.classList.add("hidden")}
bind();
})();